version: '3'
services:
    haproxy:
        container_name: lb
        build:
            context: ..
            dockerfile: Dockerfile
            args:
              LEADER_PASSWORD: ${LEADER_PASSWORD}
        environment:
            - CERTS=kano.pilot.drive.sunet.dev
            - EMAIL=kano@sunet.se
        volumes:
            - '$PWD/letsencrypt:/etc/letsencrypt'
        networks:
            - lbnet
        ports:
            - '80:80'
            - '443:443'
        image: 'tomdess/haproxy-certbot:latest'
    nginx:
        container_name: www
        networks:
            - lbnet
        image: nginx
    rsyslog:
        container_name: rsyslog
        environment:
            - TZ=UTC
        volumes:
            - '$PWD/data/rsyslog/config:/config'
        networks:
            - lbnet
        ports:
            - '514:514'
        image: 'rsyslog/syslog_appliance_alpine'

networks:
  lbnet:
